### ISSUE TITLE
Bugs in the Current Version

### ISSUE THREAD

**Issue by yongjun1** [xmf-xmodeler/XModeler#2]
1. Persistence: Images can be stored, but not loaded
2. Comments in OCL code, when edited inside XModeler, disappear when the code is committed (right-click + 'commit changes')
3. In the properties view of a constructor of a class, when import parameters are declared, they are automatically made available to the constructor's implementation by auto-generating a 'let'-statement at the beginning of the constructor's source code. Then, when code is committed, the let statement is repeatedly added to the head of the source code, resulting in multiple redundant let statements. 

e.g., initially: 
let value = self.value in self 
end
after “Commit Changes”: 
let value = self.value 
in 
let value = self.value
in self 
end 
end

**Comment by jgulden** [comment]
We simply add some more issues here. Are we going to split these up into individual bug tickets later?
1. When slot values referencing other instances in the model are set programmatically on the instance level, no corresponding arrow appears in the visualized snapshot diagram.
2. When code in a constructor implementation is committed, an additional operation named "anonymous" appears as member of the class, which contains the same implementation code as the constructor. If "anonymous()" is deleted, however, everything seems to keep on working. So is the additional operation "anonymous()" needed at all?
3. It is difficult to reference the entire model snapshot from a single object contained in the model. This is typically necessary to offer user-dialogs where existing instances in a model can be selected objects to be referenced.
4. When source code with mistakes is being committed, it sometimes takes multiple minutes until the OCL compiler comes up with an error message. It is especially confusing that in these cases the background of the editor text-field first turns white immediately (as if the commit succeeded), but the error message and turning the background color to red comes much later. The editor shouldn't switch to white until successful compilation has been performed. There should be a progress-bar to indicate whether compiling still goes on.
5. Linux and Mac builds of XModeler should be available besides the Windows version.

**Comment by yongjun1** [comment]
yes, I will do it later after we have a look. thanks.

**Comment by jaapb** [comment]
I've now split all the issues in separate ones. And yes, let's add separate bugs/enhancements/issues/... separately in the future so we can deal with them properly. Thanks!
