### ISSUE TITLE
XModeler crashes when program creates large data structures

### ISSUE THREAD

**Issue by jgulden** [xmf-xmodeler/XModeler#20]
Program code that uses a lot of memory can cause the XModeler to crash, i.e., make the window of the Eclipse environment suddenly disappear. The garbage collector sometimes outputs some messages beforehand, which show a decreasing amount of "available" memory, going down to 0. Then the application crashes.

The problem can be reproduced by invoking the following test (after loading the attached source files, see below):

TreeProblem::Tree("r", 10, 6); (try higher numbers if you do not experience the described behaviour)

=== Manifest.xmf ===
parserImport Manifests;

@Manifest Benchmarking

  p = @File  Tree               end 

  do p

end;

=== Tree.xmf ===
parserImport XOCL;

context Root

@Package TreeProblem metapackage Root::XCore extends Root::XCore
 @Class Tree extends Class
        @Attribute children : Set(Tree) end
        @Attribute level : Integer end
        @Attribute num_children : Integer end
        @Attribute value : String end

```
    @Constructor(value,num_children,level) 
        let level = self.level;
            num_children = self.num_children;
            value = self.value;
            i = 1;
            name_gen = "";
            inst = null
        in
            if self.level > 1 then
                self.children := Seq{};
                @While i <= self.num_children do
                    name_gen := self.value + i;
                    inst := Root::TreeProblem::Tree(name_gen,self.num_children, self.level-1);
                    self.children := self.children->including(inst);
                    i := i + 1
                end
            end 
        end 
    end 
end
```

end

**Comment by yongjun1** [comment]
refer to 25#
