### ISSUE TITLE
case-insensitive filename handling should be avoided

### ISSUE THREAD

**Issue by jgulden** [xmf-xmodeler/XModeler#23]
Filenames sometimes are handled case-insensitive, which causes misbehaviour on Linux systems. The following excerpt is from com.ceteva.xmf/Clients/TextEditor/FileEditorManager.xmf, the "toLower()" in line 2 causes text files with capital letters in their path to not open properly.

 @Operation edit(file:File,editable:Boolean)
      let filename = file.fullPath().toLower()
      in
        if filename.fileExists()
        then
          if fileEditorTable.hasKey(filename)
          then
            self.showFileEditor(fileEditorTable.get(filename))
          else
            let handler = self.getHandler(file.getExtension())
            in
              self.editFile(handler,file,editable)
            end
          end
        else
          xmf.warning("File " + filename + " no longer exists.  Please refresh the file browser.")
        end
      end
    end

**Comment by yongjun1** [comment]
can take .toLower() out

**Comment by jgulden** [comment]
Can this be done in the new GUI, too? The problem has reappeared there.

**Comment by jgulden** [comment]
fixed in v2
