### ISSUE TITLE
05/12/13 Mdx meeting

### ISSUE THREAD

**Issue by yongjun1** [xmf-xmodeler/XModeler#3]
At that meeting we would need to work out a target platform technology, review the current architecture and establish a plan of action.

To see how the current version works you can look at the various com.ceteva.X projects on github where X is: basicIO, client, console, diagram, dialogs, forms, menus etc. These represent the Java code for clients that process messages from the XMF engine and that send events to the XMF engine. Within the Xmodeler project com.ceteva.xmf/Clients there are corresponding folders containing the XOCL code that process the events from the Java clients and send messages to the Java clients. In principle, we should be able to do a like-for-like port by reimplementing the Java clients. If we re-implement them in Java then much of the code may be reusable. Of course we may decide that there is a much better way of doing it.

**Comment by jaapb** [comment]
(keeping notes of meetings is probably not something we want to do in the issue system)
