### ISSUE TITLE
Property Editor Navigation Functionality is Incomplete

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#33]
The property editor shouls have navigation icons (arrows?) that are used to navigate back through the stack of edited objects. For example, X.edit() should produce a property editor on X, double clicking on one of the property values of X, should produce an editor on that value. From that position it should be possible to return to Object via a single click.

In addition, once a property editor has been created via X.edit(), it is not possible to enter Y.edit() (e.g. via the console) to get a property editor for Y.

The label on the property editor currently is ‘Property’. This should be a string representation of the currently edited value.

**Comment by yongjun1** [comment]
resolve it
