### ISSUE TITLE
Tool Palettes are associated to Diagrams

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#38]
A diagram (as managed by the diagram client) consists of two elements:

(1) The tool palette containing selectable elements (such as class and association) for drawing.
(2) The pane on which the diagram is drawn

Each time a new diagram is created in XModeler, the server sends a message to the client to create a pair consisteing of both (1) and (2) that is subsequently managed as a unit.

The same palette is _never_ shared between two different diagrams.

Selecting a diagram (via double click in the browser) should cause the diagram to be shown via the diagram client consisting of both the palette and the diagram pane that is associated with the selected diagram.

Although currently there are only two main palettes that are used: class diagrams and object diagrams, in principle a diagram may be user defined (as a sub-class of Diagram) where the user code has defined a completely different palette. XTools works this way. Therefore, client code must never assume anything about the contents of the palette and must simply respond to messages that inform it of the palette contents.

**Comment by yongjun1** [comment]
resolve it
