### ISSUE TITLE
21/11/13 meeting

### ISSUE THREAD

**Issue by yongjun1** [xmf-xmodeler/XModeler#4]
(1) Jaap/Yong to work out how to manage bugs/issues/features via github.

(2) Using (1) Ulrich will populate bugs/issues/features.

(3) Using (2) MDX will review, determine dependencies and estimate effort.

(4) Using (3) MDX, DE to jointly prioritise fixes, extensions etc.

(5) Implement (4) as a plan.

(6) MDX to review the current tool architecture and to propose a migration path that:

```
(a) Disengages from Eclipse.

(b) Ensures portability and extensibility.

(c) Produces an Xmodeler on XMF 2.x

(e) Optionally establishes a basis for a family of tools running on different platforms.
```

(7) Some of the issues that need to be addressed constitute contributions to knowledge. Therefore we should keep in mind papers that can arise from this work.

Once (5) is underway we should have a mechanism to keep track of progress. Perhaps a skype call every few weeks?

We also planned a trip to DE in Q1 next year. Feb may be difficult for me so perhaps we could think about early March?

**Comment by jaapb** [comment]
(if we have issues/things to do/... arising from a meeting, let's add them as separate issues, not as meeting notes)
