### ISSUE TITLE
Property Editor: Maximise Documentation

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#54]
Clicking on ‘Maximise’ for documentation in a property editor displays the text in a single property pane correctly. But (on a Mac) the documentation overlays the property editor for the documented element. In the original XModeler, ‘Maximise’ creates a new tab. I think this is the correct behaviour.

In addition. Once ‘Maximise’ has happened, editing any other objects will not create a new property editor.

This also applies to maximising operation definitions.

**Comment by yongjun1** [comment]
resolve it
