### ISSUE TITLE
Snapshot diagrams: new object

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#57]
Cannot create a new object on a snapshot diagram.

This seems to be because the underlying dialog that asks the user to select a class to instantiate is not displayed.

In general some of the dialogs seem to be ignored (perhaps not implemented?). Try xmf.question(“?”) for an example of a working dialog.

**Comment by yongjun1** [comment]
resolve it, DialogsClient receive the message to create the diaglog
