### ISSUE TITLE
Editing File from Property editor Exception Tree

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#58]
When an operation is shown in a tree in the property editor (usually via an exception backtrace) it should be possible to double click on the operation and for the source code to appear in a text editor.

Currently this works except that it causes the system to crash.

For exmaple: type x in the console causes in unbound variable error. Open up the the first node in the exception trace and double click on the operation Root::OCL::Var::eval. This creates a text editor on the file containing the definition of the operation - correctly. Then crashes.

**Comment by yongjun1** [comment]
put the "com.ceteva.xmf.system" in the same folder of the Java GUI project (that is the reason cause exceptions when editor receive message from XMF)
