### ISSUE TITLE
Shutdown Protocol

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#65]
When the user tries to shut down XModeler (via the dropdown menu or the kill process button on the tool window). It should send a ‘shutdown’ event to the com.ceteva.mosaic client. This provides the tool with the option of taking action (such as saving state). The default (defined in MosaicEventHandler) is to ask for confirmation. If the user acknowledges shutdown then XMF sends a ‘shutdown’ command back to the client at which point the whole thing can be shut down.

**Comment by yongjun1** [comment]
resolve it, override the SWT.close event and send the "shutdown" message to XMF
