### ISSUE TITLE
Deleting Property Editor

### ISSUE THREAD

**Issue by TonyClark** [xmf-xmodeler/XModeler#73]
Once a property editor is deleted by clicking on the ‘X’ on the tab, no further objects can be edited. In addition subsequent edits can cause a system crash:

Class.edit() -> produces proerty editor
Delete the property editor
Class.edit() -> has no effect
Object.edit() -> system crash

**Comment by yongjun1** [comment]
resolve it, override the CTabltem.dispose event.
